# create your drupal and postgres config here, based off the last assignment
version: '2'

services:
  drupal:
    build: .
#      context: .
#      dockerfile: Dockerfile
    image: custom-drupal
    ports:
      - "80:80"
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles       
      - drupal-sites:/var/www/html/sites      
      - drupal-themes:/var/www/html/themes
  
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=adminadmin
      - MARIADB_DATABASE=drupal
      - MARIADB_USER=drupal
      - MARIADB_PASSWORD=drupal123
    volumes:
      - drupal-data:/var/lib/mysql

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data: